### ISSUE TITLE
MaterialX View seem to render constantly even if nothing is changing

### ISSUE THREAD

**Issue by laserallan** [materialx/MaterialX#228]
Having the materialX viewer open makes my laptop's fans spin. It seems like it's rendering regardless if anything changed since last frame.
![image](https://user-images.githubusercontent.com/1781787/58973192-44876680-87b7-11e9-95aa-da52d509e6e5.png)

**Comment by jstone-lucasfilm** [comment]
This is a good point, and we were originally torn as to whether NanoGUI should be invoked with or without a refresh timer.  This functionality is controlled through the first argument to the nanogui::mainloop function, which is invoked in Main.cpp of the viewer:

https://github.com/materialx/MaterialX/blob/master/source/MaterialXView/Main.cpp#L143
https://nanogui.readthedocs.io/en/latest/api/function_common_8h_1a1c77aa8fab708a85cb38fcad09bb4b2c.html#_CPPv4N7nanogui8mainloopEi

Since there are valid use cases for each behavior, perhaps we need a command-line argument to MaterialXView, specifying whether a refresh timer is desired.

**Comment by laserallan** [comment]
Thanks. I changed it to 1000 and it made the issue go away for me. I guess a correct solution would need to take things such as the time node in consideration so I didn't bother to submit a change list or anything.
