### ISSUE TITLE
Importing MaterialX.PyMaterialXGenOsl or MaterialX.PyMaterialXGenGlsl errors.

### ISSUE THREAD

**Issue by alister-chowdhury** [materialx/MaterialX#359]
Attempting to import either of these modules results in an error to the tune of:
```python
>>> import MaterialX.PyMaterialXGenOsl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: PyMaterialXGenShader.cpython-37m-x86_64-linux-gnu.so.1: cannot open shared object file: No such file or directory
```
In both python 2 and python 3.
It appears `MaterialX.PyMaterialXGenShader` needs to be imported first.

```python
>>> import MaterialX.PyMaterialXGenGlsl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: PyMaterialXGenShader.so.1: cannot open shared object file: No such file or directory
>>>
>>> import MaterialX.PyMaterialXGenShader
>>> import MaterialX.PyMaterialXGenGlsl
>>> import MaterialX.PyMaterialXGenOsl
```

I'm not sure if these modules, are intended to act as an implementation detail (as none of these modules are imported in the `main.py` / `__init__.py` files).

Assuming they are expected to be used explicitly, a simple (and inelegant) solution, would be to simply do an import (in the working order) in `main.py`.

**Comment by jstone-lucasfilm** [comment]
Hi Alister,

The intent is for these modules to be imported explicitly as needed, since applications are often interested in only a single shading language for generation and rendering.  I agree, though, that it's unexpected for PyMaterialXGenShader to be required before PyMaterialXGenGlsl or PyMaterialXGenOsl may be used.  My sense is that PyMaterialXGenShader should be imported automatically when either of the language-specific shader generators are imported.

Adding @niklasharrysson and @bernardkwok to the thread for their thoughts.

**Comment by jstone-lucasfilm** [comment]
Thanks to @alister-chowdhury for bringing this up, and see pull request #411 for further discussion.  For now, I'm closing out the original issue, and we can add Python wrappers for common import sequences as needed in the future.
