### ISSUE TITLE
Trying to recreate basic shapes

### ISSUE THREAD

**Issue by fire** [materialx/MaterialX#409]
This is more of a user question, but how to generate these basic shapes (square and a disc) without using a texture in MaterialX?

> Square, Disc, Paraboloid, Bell, Gaussian, Thorn, Pyramid, Brick, Gradation, Waves, Half Bell, Ridged Bell, Crescant, Capsule, Cone, Hemisphere

> https://docs.substance3d.com/sddoc/shape-159450957.html

The philosophy section of MaterialX says we're supposed to generate new nodes from the basic nodes. However, I was hoping to see if anyone has done this.

**Comment by fire** [comment]
I was able to proceed using tiledimage node. Still trying materialx.

**Comment by laserallan** [comment]
@fire I can try make examples of a few of them. Just to make sure I understand you correctly, you when talking about cones, hemisphere etc, are you referring to a "height map" version of them?

**Comment by fire** [comment]
These ones.

![image](https://user-images.githubusercontent.com/32321/80529688-a8c19480-894c-11ea-823c-bd23a31273d5.png)

The disc and the square are used like this.

![Screen Shot 2020-04-28 at 12 36 26 PM](https://user-images.githubusercontent.com/32321/80529816-e8887c00-894c-11ea-8a18-73f48e8721f9.png)

**Comment by fire** [comment]
![waves](https://user-images.githubusercontent.com/32321/80530060-4fa63080-894d-11ea-8546-bddc5d6883c1.png)

You can see how it becomes this.

**Comment by fire** [comment]
If it wasn't clear, I'm trying to see if it was feasible to convert a random Substance material to MaterialX as a proof of concept to using it to generate texture sheets at runtime or baked for Godot Engine.

https://source.substance3d.com/collections/3aedc4845410773a7ad50d044902ffbe67c85261/asset/4f9e65d3226393b51b69ee20b3c18e585958f97a

**Comment by laserallan** [comment]
Ok, I'll see what I can do to help you get started

**Comment by laserallan** [comment]
I made an intial attempt on some of the shapes using the Designer MaterialX plugin.
Let me know if this is roughly what you are looking for. As opposed to the ordinary Designer versions these are built around a coordinate system from (-1, -1)(1, 1) with the center at (0,0).

Let me know if it helps. I'd be happy to share the source sbs too if you are interested.
[Shapes.zip](https://github.com/materialx/MaterialX/files/4548411/Shapes.zip)

**Comment by fire** [comment]
I think it's easiest to make sure both source sbs and the materialx files are shared.

Are there any other visual materialx editors?

**Comment by laserallan** [comment]
Not sure if there are any out for the public.
I've attached the source sbs here.
Since the subgraph support is pretty crippled you need to do the following to use it:
1. Load Shapes.sbs
2. Run Export Subgraphs and make sure all subgraphs are selected
3. Restart Designer
4. Now you can load TestShapes to see the results and instantiate the shapes yourself

The underlying issue for the somewhat cumbersome workflow is Designer can't reload MDL modules on the fly and we model MaterialX nodes as MDL nodes. When exporting subgraphs it will 
1. Create MaterialX documents for the graphs in <userdocs>/Allegorithmic/Substance Designer/sdmatx/mtlx
2. Create MDL versions of these graphs in <userdocs>/Allegorithmic/Substance Designer/sdmatx/mdl

Since the GLSL generation is not limited by the reload issue you can iterate on the inside of a graph if was known by the last restart and reexport it until your implementation works as long as you 
1. Don't change anything about the exposed inputs or return type.
2. Use the GL viewport

[shapes_sd.zip](https://github.com/materialx/MaterialX/files/4550412/shapes_sd.zip)

**Comment by jstone-lucasfilm** [comment]
Major thanks to @laserallan for providing these example graphs, and we should discuss their inclusion as standard graph-based nodes in a future revision of MaterialX.

As David notes, Substance Designer is the first publicly-available tool for visual editing of MaterialX graphs, and the upcoming LookdevX package from Autodesk is likely to be the second.  Early video of LookdevX can be found in this GTC 2020 presentation from Autodesk and Nvidia:

https://developer.nvidia.com/gtc/2020/video/s21469

**Comment by fire** [comment]
After discussion with a few people, I think I'm going to wait a bit until there is an MaterialX import from a visual editor.

My plan was to take the GLSL generated from the genGLSL stage and change the snippets so it's compatible with Godot Engine shaders. 

Godot Engine 3.2 stable uses GLES 3 shaders, while Godot Engine master uses GLSL from Vulkan which is 450.

https://docs.godotengine.org/en/3.1/tutorials/shading/shading_reference/shaders.html

**Comment by jstone-lucasfilm** [comment]
That sounds very reasonable, and thanks for your original question.  We'll keep the MaterialX forum updated with information about Substance Designer, LookdevX, and other upcoming tools.
