### ISSUE TITLE
Potential Bug: setNode() method for NodeDef() and ShaderRef() elements

### ISSUE THREAD

**Issue by lvxejay** [materialx/MaterialX#42]
Example of the bug has been posted below. Current workaround is to use `setAttribute('node', 'somenode')`

```
temp_output = self.document.getNodeDef('material_output')
temp_output.setNode('new_output_node')
AttributeError: 'MaterialX.PyMaterialX.ShaderRef' object has no attribute 'setNode'
```

**Comment by jstone-lucasfilm** [comment]
Hey Jared -- MaterialX v1.35.4 adds a 'string' suffix to all accessors for 'node' and 'nodedef' strings, so the name of that method is now NodeDef.setNodeString.

The motivation for that change is to make a clearer distinction between methods that take a string argument (e.g. setNodeString), and methods that take an object argument (e.g. setNode).

Here's the full list of API changes in v1.35.4, so that you have a sense of what to look out for:

https://github.com/materialx/MaterialX/blob/master/CHANGELOG.md
