### ISSUE TITLE
Swapped remap/ramp OSL samples?

### ISSUE THREAD

**Issue by donmccurdy** [materialx/MaterialX#621]
[mx_remap_float.osl](https://github.com/materialx/MaterialX/blob/main/libraries/stdlib/osl/mx_remap_float.osl) looks suspiciously similar to [mx_ramp4_float.osl](https://github.com/materialx/MaterialX/blob/main/libraries/stdlib/osl/mx_ramp4_float.osl), did something get misplaced here? Also seems to apply to other remap files. I did find the expected implementation is in [mx_func.osl](https://github.com/materialx/MaterialX/blob/main/libraries/stdlib/osl/mx_funcs.h#L140) though.

**Comment by jstone-lucasfilm** [comment]
That's a good catch, @donmccurdy.  But I should note that these are the original reference implementations of the MaterialX nodes in OSL, which were authored many years ago at SPI.  The modern OSL code generator for MaterialX uses the following library instead:

https://github.com/materialx/MaterialX/tree/main/libraries/stdlib/genosl

And the implementation of <ramp4> in MaterialX 1.38 is now a language-independent node graph:

https://github.com/materialx/MaterialX/blob/main/libraries/stdlib/stdlib_ng.mtlx#L853

This issue is a good reminder, though, that we've long been planning to remove these reference OSL definitions from the repository, replacing them with a script that invokes the modern OSL code generator to produce reference implementations of each node on demand.  This would guarantee that the reference definitions stay in sync with the latest code generators, and would allow us to remove this older set of definitions from the repository.

I'd recommend that we keep this issue active until we follow through on that planned change, replacing the reference OSL definitions with their code-generated equivalents.

**Comment by jstone-lucasfilm** [comment]
Thanks for this report, @donmccurdy, and the hardcoded reference OSL shaders have been replaced with code-generated equivalents in https://github.com/materialx/MaterialX/pull/820.  For now, these code-generated reference shaders are uploaded as part of unit tests in GitHub Actions, and in the future we're planning to include them in MaterialX releases.
