### ISSUE TITLE
MATERIALX_INSTALL_STDLIB_PATH is used before it is defined

### ISSUE THREAD

**Issue by yurivict** [materialx/MaterialX#727]
It is first used used [here](https://github.com/materialx/MaterialX/blob/main/CMakeLists.txt#L52) and then is defined [here](https://github.com/materialx/MaterialX/blob/main/CMakeLists.txt#L58).

**Comment by jstone-lucasfilm** [comment]
Good observation, @yurivict, and it looks like the order of those two blocks need to be swapped within our root-level CMake.  If you already have a local fix, feel free to post a pull request; otherwise, we'll plan to take a look on our side.

If you decide to post a pull request for this issue or any others on the MaterialX project, make sure to fill out a [Contributor License Agreement](https://github.com/materialx/MaterialX/blob/main/CONTRIBUTING.md) so that we can integrate your work.

**Comment by jstone-lucasfilm** [comment]
Thanks for the report, and this has been fixed in pull request #740.
