### ISSUE TITLE
Different translucent closure def in stdosl.h compared to OSL

### ISSUE THREAD

**Issue by rasmusbonnedal** [materialx/MaterialX#778]
There is a copy of `stdosl.h` in this repo that has a conflicting declaration of `translucent()` compared to the OSL repo. The MaterialX version has an extra parameter, `sigma`. After discussion with @niklasharrysson this version of `stdosl.h` is probably from Arnold.

The extra parameter results in an assert() triggered in OSL when running a shader generated from MaterialX and compiled against the MaterialX `stdosl.h`. Does `stdosl.h` need to exist in MaterialX anymore?

### MaterialX version:
https://github.com/materialx/MaterialX/blob/a78d13f6069a6fc42eb66ab7105277a3462c36a0/libraries/stdlib/osl/stdosl.h#L545

### OSL version of `src/shaders/stdosl.h`:
```c++
closure color translucent(normal N) BUILTIN;
```
https://github.com/AcademySoftwareFoundation/OpenShadingLanguage/blob/15e0273eec28b48b5714064bacf27093c2503a30/src/shaders/stdosl.h#L455

**Comment by kwokcb** [comment]
This is the the implementation from SPI which hasn't been kept up. I thought that this wasn't isn't currently used for OSL code generation. i.e. only the `genosl` libary folder was used. 

Thus Iwhen compiling this folder should not be used to get the base definitions.
Does that sound correct, @niklasharrysson ?

**Comment by rasmusbonnedal** [comment]
When I generate OSL with `main` as of today it includes `mx_funcs.h` which is in `libraries/stdlib/osl`, same as `stdosl.h`. I need to add this directory to the include path of `oslc` to compile and then it will pick stdosl.h from MaterialX.

**Comment by kwokcb** [comment]
The test suite is set it up to require a shader include path + exe path (for oslc or testrender testing) as part of the build process so didn't notice this before. 

So your saying if the include path is not set then it will pick up this conflicting version. This would be good to address.
 
 There has be previous discussion about what to do with the `osl` library. Adding a ping to @niklasharrysson  and @jstone-lucasfilm as there were thoughts to run code gen on genosl to produce the code snippets here, but unsure what to do with the std osl definitions. _Perhaps just remove them to force users to set an include path ?_

**Comment by niklasharrysson** [comment]
Thanks @rasmusbonnedal for logging this. We need to clean this up!

The implementations in `libraries/stdlib/osl` are old and not maintained, so I think it would make sense to remove this folder completely. They were implemented and contributed by SPI back in the yearly days, and they served as a great reference implementation for MaterialX stdlib back then. But since we now have OSL code generation which is where dev resources are spent, the old static implementations could be removed. Also to avoid confusion as to what implementations to use for OSL.

These implementations exists in the OSL repo anyway (as templates that can be generated into shaders): 
https://github.com/AcademySoftwareFoundation/OpenShadingLanguage/tree/2120647911af732f0d12d70e2f7f4e1ebe8fadcb/src/shaders/MaterialX

If we remove the folder we also remove the old OSL headers. And we should use the headers from the OSL project instead. We already have a MATERIALX_OSL_INCLUDE_PATH variable to point these out, that codegen can use.

**Comment by jstone-lucasfilm** [comment]
That would be a great change, @niklasharrysson, though I've heard there are still users of the standalone OSL implementations in `libraries/stdlib/osl` that we should consider.  If we were to add support for shader generation of standalone functions, that approach could then cleanly replace the `libraries/stdlib/osl` folder with modern equivalents that are generated on demand.

**Comment by niklasharrysson** [comment]
@jstone-lucasfilm We have the ability to generate shaders for standalone nodes. There is a test case in our test suite that generate separate shaders for all nodes in stdlib. Running this will generate a directory `libraries/stdlib/reference/osl` with shaders for all nodes: https://github.com/materialx/MaterialX/blob/main/source/MaterialXTest/MaterialXRenderOsl/GenReference.cpp#L150

There are a few nodes that don't produce a correct general shader yet (the swizzle node is one case I recall), but if we fix this it might be a good alternative to replace the old unmaintained nodes in `libraries/stdlib/osl`.

**Comment by jstone-lucasfilm** [comment]
@niklasharrysson Ah, that's great to know!  In that case, perhaps it makes sense to replace the legacy reference OSL folder with their generated equivalents now, even if there are edge cases such as <swizzle> that aren't yet handled, so that we remove any confusion about which OSL shaders are canonical.  We can then refine the standalone generators over time to handle these edge cases as well.

What are your thoughts?

**Comment by niklasharrysson** [comment]
Sounds good! And I agree it makes sense to make the switch even if there are some edge cases that are not perfect yet in the generated versions. Since the legacy shaders hasn't been updated for years there are probably more issues with them anyway.

One thing to consider is if we should replace the legacy shaders with new versions of pre-generated shaders, that we update from time to time. Or if it would be better to let users generate the reference on demand? Or even have the generation as an optional build step?

**Comment by jstone-lucasfilm** [comment]
That last suggestion is the one I've been imagining we would use, where the generation of standalone OSL functions is an optional build step for MaterialXGenOsl.  That would keep the generated functions in sync with the latest libraries, and they would be included as part of the build artifacts for each version of MaterialX.

**Comment by jstone-lucasfilm** [comment]
Or perhaps better yet, we would add a C++ method with a Python binding for the generation of OSL reference functions, and then invoke this Python command from a script in our GitHub Actions build matrix.

**Comment by kwokcb** [comment]
I like the Python'ed version (or just write it all in Python ?) There can be a generatefunction() equialent to generateshader() and anyone can generate functions for any supported generator. For example, even GLSL has tokenized code so folks could generate the runnable version this way.

**Comment by niklasharrysson** [comment]
Sounds good! The unit test we have now could easily be turned into a C++ function with a Python binding.

For other languages like GLSL I'm not sure this is equally useful. In the OSL case the OSL API has support for constructing shading networks (called shader groups) from individual atomic shader nodes, which then can be compiled to a single OSL shader. For pure GLSL there is no such thing afaik. But I suppose it could serve as a reference for reading the source code of individual standard nodes.

**Comment by kwokcb** [comment]
Thanks for the clarification. I see the distinction now. So we are not emitting just the function per se. This is just packaging what is there already in a more public form.
There is a use case for hardware of also being able to glue together executable shaders but purely emitting functions can be split off as a different request  / issue.

**Comment by jstone-lucasfilm** [comment]
Thanks for this report, @rasmusbonnedal, and the extra copy of `stdosl.h` has been removed in pull request #820.
