### ISSUE TITLE
Documentation does not build

### ISSUE THREAD

**Issue by bfloch** [materialx/MaterialX#9]
Missing `ALL` in target?

CMake 3.9.0, CentOS 7.2

This fixes it.
~~~
--- a/documents/CMakeLists.txt                                                                                      
+++ b/documents/CMakeLists.txt                                                                                      
@@ -9,12 +9,12 @@ find_package(Doxygen)                                                                             
                                                                                                                    
 if(DOXYGEN_FOUND)                                                                                                  
     configure_file(${CMAKE_CURRENT_SOURCE_DIR}/Doxyfile.in ${CMAKE_CURRENT_BINARY_DIR}/Doxyfile)                   
-    add_custom_target(MaterialXDocs ${DOXYGEN_EXECUTABLE} ${CMAKE_CURRENT_BINARY_DIR}/Doxyfile                     
+    add_custom_target(MaterialXDocs ALL ${DOXYGEN_EXECUTABLE} ${CMAKE_CURRENT_BINARY_DIR}/Doxyfile                 
~~~

**Comment by jstone-lucasfilm** [comment]
That seems like a very reasonable improvement, and we'll test it on our local machines when we return from Siggraph.  At Lucasfilm we most commonly build the MaterialX documentation in Visual Studio, issuing a manual build request for the MaterialXDocs project, but it seems logical that documentation should be part of the "default" build target as well.

**Comment by jstone-lucasfilm** [comment]
Alas, this proposed change would run into a known limitation of CMake, which is that a custom target has no output file, and thus is always considered "out of date":

https://cmake.org/cmake/help/v3.2/command/add_custom_target.html

Given this limitation, if we were to make MaterialXDocs part of the default build target (i.e. by adding the ALL keyword), it would be rebuilt every single time, rather than only building when one of its inputs has been modified.

To my mind, it may be better to leave this pattern as it stands, where the MaterialXDocs project is not part of the default build target, and documentation builds must be specifically requested by the developer.

Any thoughts on alternative approaches?

**Comment by bfloch** [comment]
Now I understand your motivation. Thank you for clearing this up.

Let me make a point for making the documentation part of the ALL build target anyway.

I was just a bit confused as with other packages I am used to generate the documentation when an option to generate documentation is given and set.

Usually I do not build any specific targets as I have no knowledge about them as a "client" user.
I can imagine that a lot of people might find the same to be true if it is only their job to build dependencies.
The reason why I stumbled upon this is because here our build process is handled by rez. With an external/automated build process having to specify explicit targets might be at least a bit inconvenient.

For the use case you mention (developers who do frequent builds) I would expect them to simply leave MATERIALX_GENERATE_DOCS to OFF. I believe this option would satisfy their needs, until the point where they build for deployment with the documentation.

This is just how I see it but it certainly is not a big issue at all as is. Since their is no real standard for build scripts I feel both standpoints are valid. Usually I am used to the described behavior. At least I did not encounter any package yet where I would need to specify a target (for deployment) if there is an option for it. Maybe this is different with visual studio where you are used to opening the solution and picking targets. Still I could argue that "ALL" semantically implies all (valid) targets.

Anyhow thanks for the attention. Let's not waste more time over this. You provide good online documentation anyway, so feel free to do as you feel right.

All the best.

**Comment by jstone-lucasfilm** [comment]
You bring up some very good points here, but for now I think it's best to maintain a separate build step for documentation (e.g. by calling `make MaterialXDocs` or `cmake --build . --target MaterialXDocs`).  On the Lucasfilm side, we're often developing code and documentation at once, and it would be awkward to have a build step that never "completes".

If anyone has a suggestion for a robust solution that generates the full set of dependencies (i.e. between the ALL project, MaterialXDocs, and the generated output), feel free to create a pull request and we're happy to check it out.

**Comment by jstone-lucasfilm** [comment]
One more note:  I've updated the instructions for building API documentation in the Developer Guide (https://github.com/materialx/MaterialX/blob/master/documents/DeveloperGuide/MainPage.md), since our original instructions implied that you could just build the "ALL" target and get documentation as well.
